name: Lint and tests
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.9.0
      - uses: actions/checkout@v4
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test


